#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"syscall.h\"\n";

sub entry {
    my $name = shift;
    print ".global $name\n";
    print "${name}:\n";
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("uptime");
entry("cps");
entry("trace");
entry("sysinfo");
entry("setPriority");
entry("execve");
entry("getparentpid");
entry("print_pgtable");
entry("mmap");
entry("munmap");
entry("sh_var_read"); # 信号量：修改共享变量
entry("sh_var_write");#  信号量：修改共享变量
entry("sem_create"); # 信号量：
entry("sem_free");#  信号量：
entry("sem_p"); # 信号量：
entry("sem_v");#  信号量：
entry("symlink");
entry("mkf");
entry("shmgetat"); # 共享内存
entry("shmrefcount");#  共享内存
entry("sigalarm");
entry("sigreturn");
entry("connect");
entry("mqget");
entry("msgsnd");
entry("msgrcv");
entry("chmod");
entry("geti");
entry("recoveri");
entry("clone");
entry("join");